version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_app
    command: sh docker/entrypoints/django-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_app
    command: sh docker/entrypoints/fastapi-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: cornerstone
      POSTGRES_PASSWORD: cornerstone
      POSTGRES_DB: cornerstone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django
      - fastapi

volumes:
  postgres_data:
