services:
  django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    command: sh docker/entrypoints/django-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/ || exit 1"]
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    command: sh docker/entrypoints/fastapi-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cornerstone
      POSTGRES_PASSWORD: cornerstone
      POSTGRES_DB: cornerstone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-1
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django
      - fastapi
    networks:
      - backend
    restart: always

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge