version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  fastapi:   # se usar FastAPI separado
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    container_name: fastapi_app
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"

  db:
    image: postgres:14
    container_name: cornerstone_db
    environment:
      POSTGRES_USER: cornerstone
      POSTGRES_PASSWORD: cornerstone
      POSTGRES_DB: cornerstone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: cornerstone_nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
      - fastapi

volumes:
  postgres_data:
