version: "3.9"

services:
  db:
    image: postgres:15
    container_name: trusses_db
    restart: always
    environment:
      POSTGRES_USER: cornerstone
      POSTGRES_PASSWORD: cornerstone123!
      POSTGRES_DB: trussesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./app
    container_name: trusses_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/trussesdb
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  postgres_data:
