version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cornerstone
      POSTGRES_PASSWORD: cornerstone
      POSTGRES_DB: cornerstone
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cornerstone -d cornerstone"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    environment:
      DATABASE_URL: postgres://cornerstone:cornerstone@db:5432/cornerstone
      DJANGO_DEBUG: "0"
      RUN_MIGRATIONS: "1"
      CREATE_SUPERUSER: "0"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    depends_on:
      - django
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      # NÃO montar staticfiles como volume vazio; servir via proxy_pass ou copiar no build
      - staticfiles:/app/staticfiles:ro
    ports:
      - "80:80"

volumes:
  postgres_data:
  staticfiles: