services:
  - type: web
    name: cornerstone-mvp
    env: python
    plan: free
    region: oregon          # ou outra região suportada
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      gunicorn cornerstone.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers ${WEB_CONCURRENCY:-3} --timeout 60
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        # Ajustar após serviço criado (ex: cornerstone-mvp.onrender.com)
        value: "cornerstone-mvp.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://cornerstone-mvp.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: cornerstone-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WEB_CONCURRENCY
        value: "3"

databases:
  - name: cornerstone-db
    plan: free