# Generated by Django 4.2.11 on 2025-09-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(blank=True, default='', max_length=50)),
                ('truss_number', models.CharField(blank=True, default='', max_length=50)),
                ('tipo', models.CharField(blank=True, default='', max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('ply', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('tamanho', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truss',
                'verbose_name_plural': 'Trusses',
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
