# Generated by Django 4.2.11 on 2025-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeTruss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truss_id', models.CharField(max_length=50)),
                ('unit_number', models.PositiveIntegerField(default=1)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('span', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('produced', models.BooleanField(default=False)),
                ('production_date', models.DateTimeField(blank=True, null=True)),
                ('producer_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'qr_codetrusses',
                'managed': False,
            },
        ),
    ]
