# Generated by Django 4.2.11 on 2025-10-31 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truss_id', models.CharField(max_length=50)),
                ('serial_number', models.PositiveIntegerField(default=1)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('span', models.CharField(max_length=20)),
                ('produzida', models.BooleanField(default=False)),
                ('data_producao', models.DateTimeField(blank=True, null=True)),
                ('produzido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('truss_id', 'serial_number')},
            },
        ),
    ]
