# Generated by Django 4.2.11 on 2025-11-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_truss_create_date_truss_floor_truss_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truss',
            name='produzido_por_nome',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
