# Generated by Django 4.2.11 on 2025-11-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_truss_produzido_por_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truss',
            old_name='produzida',
            new_name='produced',
        ),
        migrations.RenameField(
            model_name='truss',
            old_name='produzido_por_nome',
            new_name='producer_name',
        ),
        migrations.RenameField(
            model_name='truss',
            old_name='data_producao',
            new_name='production_date',
        ),
        migrations.RenameField(
            model_name='truss',
            old_name='quantidade',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='truss',
            old_name='table_name',
            new_name='table_number',
        ),
        migrations.RemoveField(
            model_name='truss',
            name='produzido_por',
        ),
        migrations.AddField(
            model_name='truss',
            name='produced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
