# Generated by Django 4.2.11 on 2025-11-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_produzida_truss_produced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truss',
            name='produced_by',
        ),
    ]
